# Virtual threads give no gain in context of coroutines
# Blocking code (like Thread.sleep()) does not allow coroutine parallelization as it blocks the thread (even a virtual one)
# On the other hand non-blocking code (like delay()) works perfectly on good old platform threads
# spring.threads.virtual.enabled=true